"""clients, peers, prefixes tables

Revision ID: 3fdba18675c8
Revises: 
Create Date: 2022-10-28 00:14:52.659436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdba18675c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('peers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asn', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asn')
    )
    op.create_table('prefixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peer_id'], ['peers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prefixes')
    op.drop_table('peers')
    op.drop_table('clients')
    # ### end Alembic commands ###
